# Generated by Django 2.2.9 on 2020-11-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cpation',
            new_name='caption',
        ),
    ]
